In [ ]:
#Row wise iteration

import numpy as np

x=np.array([[34,56,78],[90,99,101],[21,34,67]])

def print_row(x):
  row,col=x.shape
  for i in range(row):
    for j in range(col):
      print(x[i][j],end=" ")
  print()


print_row(x)

34 56 78 90 99 101 21 34 67 


In [ ]:
#Column wise iteration


import numpy as np

x=np.array([[34,56,78],[90,99,101],[21,34,67]])

def print_row(x):
  row,col=x.shape
  for i in range(row):
    for j in range(col):
      print(x[j][i],end=" ")
  print()


print_row(x)


34 90 21 56 99 34 78 101 67 


In [ ]:
#Sum of all elements in a 2D matrix:
import numpy as np
x=np.array([[34,56,78],[90,99,101],[21,34,67]])

def sum(x):
  total=0
  row,col=x.shape
  for i in range(row):
    for j in range (col):
      total+=x[i][j]

  return total

answer=sum(x)
print(answer)

580


In [ ]:
#Row-Wise matrix summation

import numpy as np
x=np.array([[34,56,78],[90,99,101],[21,34,67]])

def row_wise(x):
  row,col=x.shape
  resulting =np.zeros((row,1),int)
  for i in range(row):
    for j in range(col):
      resulting[i][0] += x[i][j]

  return resulting

ans=row_wise(x)
print(ans)


[[168]
 [290]
 [122]]


In [ ]:
#Col-wise sum
import numpy as np
x=np.array([[34,56,78],[90,99,101],[21,34,67]])

def col_wise(x):
  row,col=x.shape
  resulting =np.zeros((1,col),int)
  for i in range(row):
    for j in range(col):
      resulting[0][j] += x[i][j]

  return resulting

ans=col_wise(x)
print(ans)


[[145 189 246]]


In [ ]:
#Matrix Swapping
# Swap the cols of a matrix (reverse,(2 pointer approach))
# Reverse col-wise

import numpy as np
x=np.array([[34,56,78],[90,99,101]])

def swap_cols(x):
  row,col=x.shape
  for i in range(row):
    for j in range (col//2):
      x[i][j],x[i][col-1-j]=x[i][col-1-j],x[i][j]

  return x

ans=swap_cols(x)
print(ans)


[[ 78  56  34]
 [101  99  90]]


In [ ]:
#Swap the rows
import numpy as np
x=np.array([[34,56,78],[90,99,101],[21,34,67]])

def swap_cols(x):
  row,col=x.shape
  for i in range(row//2):
    for j in range (col):
      x[i][j],x[row-1-i][j]=x[row-i-1][j],x[i][j]

  return x

ans=swap_cols(x)
print(ans)


[[ 21  34  67]
 [ 90  99 101]
 [ 34  56  78]]


In [ ]:
#Transpose
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])


def Transpose(x):
  row,col=x.shape
  result=np.zeros((row,col))
  for i in range(row):
    for j in range(col):
      result[i][j]=x[j][i]

  return result

ans=Transpose(x)
print(ans)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [ ]:
#Primary Diagonal Sum

import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

def PD_Sum(x):
  total=0
  row,col=x.shape
  for i in range(row):
    for j in range(col):
      if i==j:
        total+=x[i][j]
  return total


ans=PD_Sum(x)
print(ans)


15


In [ ]:
#Secondary Diagonal Sum
import numpy as np
x=np.array([[21,35,11],[49,56,81],[7,6,5]])

def SD_Sum(x):
  total=0
  row,col=x.shape
  for i in range(row):
    for j in range(col):
      if i+j==row-1:
        total+=x[i][j]

  return total


ans=SD_Sum(x)
print(ans)

74


In [ ]:
#ZigZag Traversal
import numpy as np
def walk_zigzag(floor):

  row,col=floor.shape
  for j in range(col):
    if j%2==0:
      for i in range(row):
        if(i+j)%2==0:
          print(floor[i][j],end=" ")
    else:
      for i in range(row-1,-1,-1):
        if(i+j)%2==0:
          print(floor[i][j],end=" ")
    print()


floor = np.array([[ '3' , '8' , '4' , '6' , '1'],
                  ['7' , '2' , '1' , '9' , '3'],
                  ['9' , '0' , '7' , '5' , '8'],
                  ['2' , '1' , '3' , '4' , '0'],
                  ['1' , '4' , '2' , '8' , '6']]
                )

print('Walking Sequence:')
walk_zigzag(floor)


Walking Sequence:
3 9 1 
1 2 
4 7 2 
4 9 
1 8 6 


In [ ]:

#Wall Up Trost District


def create_fence(district, depth):
    district_row, district_col = district.shape
    out = np.full((district_row + (depth*2), district_col + (depth*2)), 8, dtype = int)
    for i in range(district_row):
      for j in range(district_col):
        out[i + depth][j + depth] = district[i][j]
    return out


In [ ]:
#Crows vs Cats

def strength_difference(clubroom):
  strength_diff = np.zeros(100, dtype = int)
  m = len(clubroom)
  strength_diff = np.zeros((m*(m-1))//2, dtype = int)
  n = 0
  for i in range(1, m):
    for j in range(i):
      strength_diff[n] = clubroom[j][i] - clubroom[i][j]
      n += 1
  return strength_diff

In [ ]:
#ATM Triangle

def strength_difference(clubroom):
  strength_diff = np.zeros(100, dtype = int)
  m = len(clubroom)
  strength_diff = np.zeros((m*(m-1))//2, dtype = int)
  n = 0
  for i in range(1, m):
    for j in range(i):
      strength_diff[n] = clubroom[j][i] - clubroom[i][j]
      n += 1
  return strength_diff

In [ ]:
#Trace the Bot
def moving_around(cmds):
  grid = np.full((7, 7), '.')
  m, n = 3, 3
  grid[m][n] = '-'
  movements = np.array([
    [(-2, -2), (0, -1)],
    [(-2, -2), (0, 1)],
    [(-2, -2), (-1, 0)],
    [(-2, -2), (1, 0)],
    [(-2, 2), (0, -1)],
    [(-2, 2), (0, 1)],
    [(-2, 2), (-1, 0)],
    [(-2, 2), (1, 0)],
    [(2, -2), (0, -1)],
    [(2, -2), (0, 1)],
    [(2, -2), (-1, 0)],
    [(2, -2), (1, 0)]
  ])

  for move in cmds:
    temp_m = m
    temp_n = n
    for m1, n1 in movements[move - 1]:
      new_m = temp_m + m1
      new_n = temp_n + n1
      if new_m >= 0 and new_m < 7 and new_n >= 0 and new_n < 7:
        temp_m = new_m
        temp_n = new_n
      else:
        break
    else:
      m = temp_m
      n = temp_n
      grid[m][n] = '*'

  grid[m][n] = '/'
  return grid