In [ ]:

import numpy as np


/usr/local/lib/python3.10/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [ ]:
#Check if array is palindrome

def palindrome(arr,size):
  palin=np.array([0]*size)
  for i in range(size):
    palin[i]=arr[i]
  result=np.array([0]*size)
  i=0
  n=len(palin)
  while(i<n):
    result[i]=palin[n-1-i]
    i+=1

  if np.array_equal(result,palin):
    return True
  else:
    return False



arr= np.zeros(5, dtype=int)
arr[0], arr[1], arr[2], arr[3] = 4, 6, 6, 4
print(palindrome(arr, 4)) #array, size

arr= np.zeros(5, dtype=int)
arr[0], arr[1], arr[2] = 4, 6, 4
print(palindrome(arr, 3)) #array, size

arr= np.zeros(5, dtype=int)
arr[0], arr[1], arr[2], arr[3] = 4, 6, 4, 5
print(palindrome(arr, 4)) #array, size

True
True
False


kibhabe array theke dummy element gulo baad diye proper size a anbo

array_equal()

In [ ]:
#Reverse printing an Array

def Rev_Print(arr,size):
  reverse= np.array([0]*size)
  for i in range(size):
    reverse[i]=arr[i]

  result=np.array([0]*size)
  i=0
  n=len(reverse)
  while(i<n):
    result[i]=reverse[n-1-i]
    i+=1
  return result



arr= np.array([1,3,2 ,5 ,0 ,0])
print(Rev_Print(arr, 4)) #Array, size



[5 2 3 1]


In [ ]:
#Merge Two Arrays

def Merge_Arrays(arr1, x, arr2, y):

 m=x+y

 A=np.array([0]*x)
 for i in range(x):
    A[i]=arr1[i]

 B=np.array([0]*y)
 for i in range(y):
    B[i]=arr2[i]

 result=np.array([0]*m)
 for i in range(x):
    result[i]=A[i]
 for i in range(y):
    result[i+x]=B[i]


 return result


arr1= np.array([1, 5,0, 0])
arr2= np.array([3, 5 ,2 ,0])
print(Merge_Arrays(arr1, 2, arr2, 3)) #Array1, Array1 size, Array2, Array2 size

[1 5 3 5 2]


Concatenation =[1,2,1] >>> [1,2,1,1,2,1]

Merging = [1,2,3] & [4,5,6] >> [1,2,3,4,5,6]

In [ ]:
#BubbleSort

import numpy as np

def bubble_sort(arr):

    n = len(arr)

    # Traverse through all array elements
    for i in range(n):
        # Last i elements are already in place, so we don't need to check them
        for j in range(0, n-i-1):
            # Swap if the element found is greater than the next element
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]

    return arr

# Example usage:
my_array = np.array([6,8,5,4,90,43,21])
sorted_array=bubble_sort(my_array)
print(sorted_array)

[ 4  5  6  8 21 43 90]


In [ ]:
#Find the largest three distinct elements in an array

def largest_three(arr):

  def bubble_sort(arr):

    n = len(arr)

    # Traverse through all array elements
    for i in range(n):
        # Last i elements are already in place, so we don't need to check them
        for j in range(0, n-i-1):
            # Swap if the element found is greater than the next element
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]

    return arr

  sorted=bubble_sort(arr)


  for i in range((len(sorted)-3),(len(sorted))):
    print(sorted[i],end=",")

arr=np.array([10,4,3,50,23,90])
largest_three(arr)




23,50,90,

In [ ]:
#2nd Largest element in array





#Bubble Sort
#2nd Last element pf the sorted array

In [ ]:
#Move all zeroes to the end of array
